---
title: "hw.02"
output: html_document
---
```{r}
library(gapminder)
library(dplyr)
library(ggplot2)
```

## EX 1.1 Canada, Belgium and Bangladesh in the 1970s
```{r}
gapminder %>%
  filter(year >= "1970" & year < "1980") %>%
  filter(country == "Canada" | country == "Belgium" | country == "Bangladesh")
```

## 1.2 Above with only country and gdpPercap
```{r}
gapminder %>%
  filter(year >= "1970" & year < "1980") %>%
  filter(country == "Canada" | country == "Belgium" | country == "Bangladesh")%>%
  select(country, gdpPercap)
```

## 1.3 All entries with a drop in life expectancy
```{r}
gapminder %>%
  mutate(life.inc = c(NA, diff(lifeExp, lag = 1))) %>%
  filter(life.inc < 0)
```

## 1.4 Max GDP experienced per country
```{r}
gapminder %>%
  group_by(country) %>%
  summarise(max.gdp = max(gdpPercap))
```

## 1.5 Scatter plot of Canada's life expectancy vs. GDP per capita
```{r}
gapminder %>%
  filter(country == "Canada") %>%
  ggplot(., aes(gdpPercap, lifeExp))+
           geom_point()+
  scale_x_log10("GDP per capita", labels = scales::dollar_format())+
  ylab("Life expectancy")+
  theme_bw()
```

## EX 2 Exploring country and population
```{r}
gapminder %>%
  select(continent,lifeExp)%>%
  group_by(continent)%>%
  summarise(n.countries = n(), 
            mean.lifeExp = mean(lifeExp),
            min.lifeExp = min(lifeExp),
            max.lifeExp = max(lifeExp))
  
gapminder %>%
  select(continent, lifeExp) %>%
  group_by(continent)%>%
  summarise(n.countries =n())%>%
  glimpse()
```

## EX 3 Explore various plot types
### Scatter plot of 
```{r}
gapminder %>%
  filter(country =="Australia" | country == "China"  | country == "Japan" | country =="Indonesia") %>%
  ggplot(., aes(gdpPercap, pop, group=country))+
  scale_x_continuous("GDP per capita", labels = scales::dollar_format())+
  ylab("Population")+
  geom_point(aes(color=country))+
  theme_bw()
```





