---
title: "hw03"
output: html_document
---

```{r, echo=FALSE}
library(gapminder)
library(tidyverse)
```

##Task option 3 - The spread of GDP within the continents.
#A tibble
<!-- -->
```{r}
tibble <- gapminder %>% 
  select(gdpPercap, continent, country) %>%
  group_by(continent,country) %>%
  summarise(minGDP = min(gdpPercap),
            maxGDP = max(gdpPercap),
            meanGDP = mean(gdpPercap)) %>%
  mutate(GDPdiff = maxGDP - minGDP)
tibble
```

#A plot from the tibble
<!-- -->
```{r}
ggplot(tibble) + geom_jitter(aes(continent, meanGDP, color = continent)) + 
  labs(title="GDP per Capita of countries")
  theme_bw() +
  theme(legend.position="none")  
```

#What this figure/table show
<!-- -->

##Task option 5 - How is life expectancy changing over time on different continents
#A tibble
<!-- -->
```{r}
(lifeExp <- gapminder %>% select(country,continent,lifeExp,year)) 
```

#A plot from the tibble
<!-- -->
```{r}
ggplot(lifeExp, aes(year,lifeExp, group=continent)) + geom_smooth(aes(color=continent)) + theme_bw()
```

#What this figure/table show
<!-- -->
```{r}
gapmin
```


##Task option 6 - A country with an interesting story 
#A tibble
<!-- -->
```{r}
ggplot(gapminder, aes(year, pop,group=continent)) + geom_jitter()
gapminder %>% filter(pop>250000000)
```

#A plot from the tibble
<!-- -->
```{r}

```

#What this figure/table show
<!-- -->
```{r}

```

